package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CloudFiles generated by hbm2java
 */
@Entity
@Table(name = "cloud_files", catalog = "cms")
public class CloudFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String fileName;
	private Integer isdir;
	private String filePath;
	private Integer parentId;
	private Date createDate;
	private Integer userId;
	private Long fileSize;
	private Date lastModify;
	private String miji;
	private String saveName;
	private Byte isDeleted;
	private Boolean isSystem;

	public CloudFiles() {
	}

	public CloudFiles(String fileName, Integer isdir, String filePath, Integer parentId, Date createDate,
			Integer userId, Long fileSize, Date lastModify, String miji, String saveName, Byte isDeleted,
			Boolean isSystem) {
		this.fileName = fileName;
		this.isdir = isdir;
		this.filePath = filePath;
		this.parentId = parentId;
		this.createDate = createDate;
		this.userId = userId;
		this.fileSize = fileSize;
		this.lastModify = lastModify;
		this.miji = miji;
		this.saveName = saveName;
		this.isDeleted = isDeleted;
		this.isSystem = isSystem;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "file_Name", length = 450)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "isdir")
	public Integer getIsdir() {
		return this.isdir;
	}

	public void setIsdir(Integer isdir) {
		this.isdir = isdir;
	}

	@Column(name = "file_Path", length = 200)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "parent_Id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_Date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "user_Id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "file_Size")
	public Long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_Modify", length = 19)
	public Date getLastModify() {
		return this.lastModify;
	}

	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}

	@Column(name = "miji", length = 4)
	public String getMiji() {
		return this.miji;
	}

	public void setMiji(String miji) {
		this.miji = miji;
	}

	@Column(name = "save_Name", length = 450)
	public String getSaveName() {
		return this.saveName;
	}

	public void setSaveName(String saveName) {
		this.saveName = saveName;
	}

	@Column(name = "is_Deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "is_System")
	public Boolean getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(Boolean isSystem) {
		this.isSystem = isSystem;
	}

}
