package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HomeMessage generated by hbm2java
 */
@Entity
@Table(name = "home_message", catalog = "cms")
public class HomeMessage implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int sendUserId;
	private int receiveUserId;
	private Integer messageId;
	private String channel;
	private int createDate;
	private String content;

	public HomeMessage() {
	}

	public HomeMessage(int userId, int sendUserId, int receiveUserId, String channel, int createDate, String content) {
		this.userId = userId;
		this.sendUserId = sendUserId;
		this.receiveUserId = receiveUserId;
		this.channel = channel;
		this.createDate = createDate;
		this.content = content;
	}

	public HomeMessage(int userId, int sendUserId, int receiveUserId, Integer messageId, String channel, int createDate,
			String content) {
		this.userId = userId;
		this.sendUserId = sendUserId;
		this.receiveUserId = receiveUserId;
		this.messageId = messageId;
		this.channel = channel;
		this.createDate = createDate;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "send_user_id", nullable = false)
	public int getSendUserId() {
		return this.sendUserId;
	}

	public void setSendUserId(int sendUserId) {
		this.sendUserId = sendUserId;
	}

	@Column(name = "receive_user_id", nullable = false)
	public int getReceiveUserId() {
		return this.receiveUserId;
	}

	public void setReceiveUserId(int receiveUserId) {
		this.receiveUserId = receiveUserId;
	}

	@Column(name = "message_id")
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@Column(name = "channel", nullable = false, length = 50)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "create_date", nullable = false)
	public int getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(int createDate) {
		this.createDate = createDate;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
