package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PluginLotteryUserAttribute generated by hbm2java
 */
@Entity
@Table(name = "plugin_lottery_user_attribute", catalog = "cms")
public class PluginLotteryUserAttribute implements java.io.Serializable {

	private int lotteryUserId;
	private String data;

	public PluginLotteryUserAttribute() {
	}

	public PluginLotteryUserAttribute(int lotteryUserId) {
		this.lotteryUserId = lotteryUserId;
	}

	public PluginLotteryUserAttribute(int lotteryUserId, String data) {
		this.lotteryUserId = lotteryUserId;
		this.data = data;
	}

	@Id

	@Column(name = "lottery_user_id", unique = true, nullable = false)
	public int getLotteryUserId() {
		return this.lotteryUserId;
	}

	public void setLotteryUserId(int lotteryUserId) {
		this.lotteryUserId = lotteryUserId;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
