package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PluginSite generated by hbm2java
 */
@Entity
@Table(name = "plugin_site", catalog = "cms", uniqueConstraints = @UniqueConstraint(columnNames = { "site_id",
		"plugin_code" }))
public class PluginSite implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String pluginCode;
	private String widgetTemplate;
	private String staticTemplate;
	private String path;

	public PluginSite() {
	}

	public PluginSite(int siteId, String pluginCode) {
		this.siteId = siteId;
		this.pluginCode = pluginCode;
	}

	public PluginSite(int siteId, String pluginCode, String widgetTemplate, String staticTemplate, String path) {
		this.siteId = siteId;
		this.pluginCode = pluginCode;
		this.widgetTemplate = widgetTemplate;
		this.staticTemplate = staticTemplate;
		this.path = path;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "plugin_code", nullable = false, length = 50)
	public String getPluginCode() {
		return this.pluginCode;
	}

	public void setPluginCode(String pluginCode) {
		this.pluginCode = pluginCode;
	}

	@Column(name = "widget_template")
	public String getWidgetTemplate() {
		return this.widgetTemplate;
	}

	public void setWidgetTemplate(String widgetTemplate) {
		this.widgetTemplate = widgetTemplate;
	}

	@Column(name = "static_template")
	public String getStaticTemplate() {
		return this.staticTemplate;
	}

	public void setStaticTemplate(String staticTemplate) {
		this.staticTemplate = staticTemplate;
	}

	@Column(name = "path", length = 2000)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
