package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDomain generated by hbm2java
 */
@Entity
@Table(name = "sys_domain", catalog = "cms")
public class SysDomain implements java.io.Serializable {

	private Integer id;
	private String name;
	private int siteId;
	private String path;
	private String loginPath;
	private String registerPath;

	public SysDomain() {
	}

	public SysDomain(String name, int siteId) {
		this.name = name;
		this.siteId = siteId;
	}

	public SysDomain(String name, int siteId, String path, String loginPath, String registerPath) {
		this.name = name;
		this.siteId = siteId;
		this.path = path;
		this.loginPath = loginPath;
		this.registerPath = registerPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "login_path")
	public String getLoginPath() {
		return this.loginPath;
	}

	public void setLoginPath(String loginPath) {
		this.loginPath = loginPath;
	}

	@Column(name = "register_path")
	public String getRegisterPath() {
		return this.registerPath;
	}

	public void setRegisterPath(String registerPath) {
		this.registerPath = registerPath;
	}

}
