package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDeptPage generated by hbm2java
 */
@Entity
@Table(name = "sys_dept_page", catalog = "cms")
public class SysDeptPage implements java.io.Serializable {

	private Integer id;
	private int deptId;
	private String page;

	public SysDeptPage() {
	}

	public SysDeptPage(int deptId, String page) {
		this.deptId = deptId;
		this.page = page;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dept_id", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "page", nullable = false)
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

}
