package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysEmailToken generated by hbm2java
 */
@Entity
@Table(name = "sys_email_token", catalog = "cms")
public class SysEmailToken implements java.io.Serializable {

	private String authToken;
	private int userId;
	private String email;
	private Date createDate;

	public SysEmailToken() {
	}

	public SysEmailToken(String authToken, int userId, String email, Date createDate) {
		this.authToken = authToken;
		this.userId = userId;
		this.email = email;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "auth_token", unique = true, nullable = false, length = 40)
	public String getAuthToken() {
		return this.authToken;
	}

	public void setAuthToken(String authToken) {
		this.authToken = authToken;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
