package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysFtpUser generated by hbm2java
 */
@Entity
@Table(name = "sys_ftp_user", catalog = "cms", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SysFtpUser implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String name;
	private String password;
	private String path;

	public SysFtpUser() {
	}

	public SysFtpUser(int siteId, String name, String password) {
		this.siteId = siteId;
		this.name = name;
		this.password = password;
	}

	public SysFtpUser(int siteId, String name, String password, String path) {
		this.siteId = siteId;
		this.name = name;
		this.password = password;
		this.path = path;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
