package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogLogin generated by hbm2java
 */
@Entity
@Table(name = "log_login", catalog = "cms")
public class LogLogin implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String name;
	private Integer userId;
	private String ip;
	private String channel;
	private boolean result;
	private Date createDate;
	private String errorPassword;

	public LogLogin() {
	}

	public LogLogin(int siteId, String name, String ip, String channel, boolean result, Date createDate) {
		this.siteId = siteId;
		this.name = name;
		this.ip = ip;
		this.channel = channel;
		this.result = result;
		this.createDate = createDate;
	}

	public LogLogin(int siteId, String name, Integer userId, String ip, String channel, boolean result, Date createDate,
			String errorPassword) {
		this.siteId = siteId;
		this.name = name;
		this.userId = userId;
		this.ip = ip;
		this.channel = channel;
		this.result = result;
		this.createDate = createDate;
		this.errorPassword = errorPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ip", nullable = false, length = 64)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "channel", nullable = false, length = 50)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "result", nullable = false)
	public boolean isResult() {
		return this.result;
	}

	public void setResult(boolean result) {
		this.result = result;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "error_password", length = 100)
	public String getErrorPassword() {
		return this.errorPassword;
	}

	public void setErrorPassword(String errorPassword) {
		this.errorPassword = errorPassword;
	}

}
