package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PluginVoteItem generated by hbm2java
 */
@Entity
@Table(name = "plugin_vote_item", catalog = "cms")
public class PluginVoteItem implements java.io.Serializable {

	private Integer id;
	private int voteId;
	private String title;
	private String description;
	private int scores;
	private int sort;

	public PluginVoteItem() {
	}

	public PluginVoteItem(int voteId, String title, int scores, int sort) {
		this.voteId = voteId;
		this.title = title;
		this.scores = scores;
		this.sort = sort;
	}

	public PluginVoteItem(int voteId, String title, String description, int scores, int sort) {
		this.voteId = voteId;
		this.title = title;
		this.description = description;
		this.scores = scores;
		this.sort = sort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "vote_id", nullable = false)
	public int getVoteId() {
		return this.voteId;
	}

	public void setVoteId(int voteId) {
		this.voteId = voteId;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "scores", nullable = false)
	public int getScores() {
		return this.scores;
	}

	public void setScores(int scores) {
		this.scores = scores;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

}
