package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysApp generated by hbm2java
 */
@Entity
@Table(name = "sys_app", catalog = "cms", uniqueConstraints = @UniqueConstraint(columnNames = "app_key"))
public class SysApp implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String channel;
	private String appKey;
	private String appSecret;

	public SysApp() {
	}

	public SysApp(int siteId, String channel, String appKey, String appSecret) {
		this.siteId = siteId;
		this.channel = channel;
		this.appKey = appKey;
		this.appSecret = appSecret;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "channel", nullable = false, length = 50)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Column(name = "app_key", unique = true, nullable = false, length = 50)
	public String getAppKey() {
		return this.appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	@Column(name = "app_secret", nullable = false, length = 50)
	public String getAppSecret() {
		return this.appSecret;
	}

	public void setAppSecret(String appSecret) {
		this.appSecret = appSecret;
	}

}
