package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysAppToken generated by hbm2java
 */
@Entity
@Table(name = "sys_app_token", catalog = "cms")
public class SysAppToken implements java.io.Serializable {

	private String authToken;
	private int appId;
	private Date createDate;

	public SysAppToken() {
	}

	public SysAppToken(String authToken, int appId, Date createDate) {
		this.authToken = authToken;
		this.appId = appId;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "auth_token", unique = true, nullable = false, length = 40)
	public String getAuthToken() {
		return this.authToken;
	}

	public void setAuthToken(String authToken) {
		this.authToken = authToken;
	}

	@Column(name = "app_id", nullable = false)
	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
