package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysDept generated by hbm2java
 */
@Entity
@Table(name = "sys_dept", catalog = "cms")
public class SysDept implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String name;
	private Integer parentId;
	private String description;
	private Integer userId;
	private boolean ownsAllCategory;
	private boolean ownsAllPage;

	public SysDept() {
	}

	public SysDept(int siteId, String name, boolean ownsAllCategory, boolean ownsAllPage) {
		this.siteId = siteId;
		this.name = name;
		this.ownsAllCategory = ownsAllCategory;
		this.ownsAllPage = ownsAllPage;
	}

	public SysDept(int siteId, String name, Integer parentId, String description, Integer userId,
			boolean ownsAllCategory, boolean ownsAllPage) {
		this.siteId = siteId;
		this.name = name;
		this.parentId = parentId;
		this.description = description;
		this.userId = userId;
		this.ownsAllCategory = ownsAllCategory;
		this.ownsAllPage = ownsAllPage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "owns_all_category", nullable = false)
	public boolean isOwnsAllCategory() {
		return this.ownsAllCategory;
	}

	public void setOwnsAllCategory(boolean ownsAllCategory) {
		this.ownsAllCategory = ownsAllCategory;
	}

	@Column(name = "owns_all_page", nullable = false)
	public boolean isOwnsAllPage() {
		return this.ownsAllPage;
	}

	public void setOwnsAllPage(boolean ownsAllPage) {
		this.ownsAllPage = ownsAllPage;
	}

}
