package com.ancs.cloudFiles.models;
// Generated 2016-8-31 21:56:31 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysTask generated by hbm2java
 */
@Entity
@Table(name = "sys_task", catalog = "cms")
public class SysTask implements java.io.Serializable {

	private Integer id;
	private int siteId;
	private String name;
	private int status;
	private String cronExpression;
	private String description;
	private String filePath;

	public SysTask() {
	}

	public SysTask(int siteId, String name, int status, String cronExpression) {
		this.siteId = siteId;
		this.name = name;
		this.status = status;
		this.cronExpression = cronExpression;
	}

	public SysTask(int siteId, String name, int status, String cronExpression, String description, String filePath) {
		this.siteId = siteId;
		this.name = name;
		this.status = status;
		this.cronExpression = cronExpression;
		this.description = description;
		this.filePath = filePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "site_id", nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "cron_expression", nullable = false, length = 50)
	public String getCronExpression() {
		return this.cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "file_path")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
