package com.ancs.alphablue.models;
// Generated 2016-9-9 15:44:02 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.ancs.cms.source.entity.MyColumn;

/**
 * AlphablueProduct generated by hbm2java
 */
@Entity
@Table(name = "alphablue_product", catalog = "cms", uniqueConstraints = @UniqueConstraint(columnNames = "pname"))
public class AlphablueProduct implements java.io.Serializable {

	@MyColumn(title="ID")
	private Integer id;
	@MyColumn(title="产品名称")
	private String pname;
	@MyColumn(title="产品代码")
	private String pcode;
	@MyColumn(title="产品单价")
	private Float price;
	@MyColumn(title="产品描述")
	private String descrption;

	public AlphablueProduct() {
	}

	public AlphablueProduct(String pname, String pcode, Float price, String descrption) {
		this.pname = pname;
		this.pcode = pcode;
		this.price = price;
		this.descrption = descrption;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pname", unique = true, length = 45)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "pcode", length = 45)
	public String getPcode() {
		return this.pcode;
	}

	public void setPcode(String pcode) {
		this.pcode = pcode;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "descrption", length = 405)
	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}

}
