package com.ancs.alphablue.models;
// Generated 2016-9-9 15:44:02 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

import com.ancs.cms.source.entity.MyColumn;

/**
 * AlphablueOrder generated by hbm2java
 */
@Entity
@Table(name = "alphablue_order", catalog = "cms")
public class AlphablueOrder implements java.io.Serializable {
	@MyColumn(title = "ID", condition = true)
	private Integer id;
	@MyColumn(title = "用户", condition = true)
	private Integer userId;
	@MyColumn(title = "产品", condition = true)
	private Integer productId;
	@MyColumn(title = "数量", condition = true)
	private Integer count;
	@MyColumn(title = "价格", condition = true)
	private Float allprice;
	@MyColumn(title = "收货人", condition = true)
	private String receiver;
	@MyColumn(title = "收货人地址", condition = true)
	private String address;
	@MyColumn(title = "收货人电话", condition = true)
	private String telphone;
	@MyColumn(title = "订单类型", condition = true)
	private String ordertype;
	@MyColumn(title = "折扣", condition = true)
	private Float discount;

	@MyColumn(title = "邮政编码")
	private String userZipcode;

	@MyColumn(title = "创建时间")
	private Date createdate;

	@MyColumn(title = "付款时间")
	private Date paydate;

	@MyColumn(title = "作废时间")
	private Date outdate;

	public AlphablueOrder() {
	}

	public AlphablueOrder(Integer userId, Integer productId, Integer count, Float allprice, String receiver,
			String address, String telphone, String ordertype, Float discount, String userZipcode) {
		this.userId = userId;
		this.productId = productId;
		this.count = count;
		this.allprice = allprice;
		this.receiver = receiver;
		this.address = address;
		this.telphone = telphone;
		this.ordertype = ordertype;
		this.discount = discount;
		this.userZipcode = userZipcode;
	}

	public AlphablueOrder(Integer id, Integer userId, Integer productId, Integer count, Float allprice, String receiver,
			String address, String telphone, String ordertype, Float discount, String userZipcode, Date create,
			Date paydate, Date outdate) {
		super();
		this.id = id;
		this.userId = userId;
		this.productId = productId;
		this.count = count;
		this.allprice = allprice;
		this.receiver = receiver;
		this.address = address;
		this.telphone = telphone;
		this.ordertype = ordertype;
		this.discount = discount;
		this.userZipcode = userZipcode;
		this.createdate = create;
		this.paydate = paydate;
		this.outdate = outdate;
	}

	@Column(name = "createdate", nullable = true, length = 19)
	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date create) {
		this.createdate = create;
	}

	@Column(name = "paydate", nullable = true, length = 19)
	public Date getPaydate() {
		return paydate;
	}

	public void setPaydate(Date paydate) {
		this.paydate = paydate;
	}

	@Column(name = "outdate", nullable = true, length = 19)
	public Date getOutdate() {
		return outdate;
	}

	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "allprice", precision = 12, scale = 0)
	public Float getAllprice() {
		return this.allprice;
	}

	public void setAllprice(Float allprice) {
		this.allprice = allprice;
	}

	@Column(name = "receiver", length = 450)
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "address", length = 450)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "telphone", length = 450)
	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	@Column(name = "ordertype", length = 450)
	public String getOrdertype() {
		return this.ordertype;
	}

	public void setOrdertype(String ordertype) {
		this.ordertype = ordertype;
	}

	@Column(name = "discount", precision = 12, scale = 0)
	public Float getDiscount() {
		return this.discount;
	}

	public void setDiscount(Float discount) {
		this.discount = discount;
	}

	@Column(name = "user_zipcode")
	public String getUserZipcode() {
		return userZipcode;
	}

	public void setUserZipcode(String userZipcode) {
		this.userZipcode = userZipcode;
	}

}
